### ISSUE TITLE
Versioning issues with `pandas` and `pypsa`

### ISSUE THREAD

**Issue by degleris1** [ktehranchi/pypsa-breakthroughenergy-usa#16]
It seems that in later versions of `pandas`, the function `DatetimeArray._generate_range()` doesn't support the keyword argument `closed`. Setting `pandas=1.5.3` seems to fix the issue. 

Similarly, some versions of `pypsa` produce import errors in `pypsa.networkclustering`. For example, `pypsa=0.18` cannot import `busmap_by_hac`.

@jackaglad Can you add you `conda list` output here? As well as the import errors.

@ktehranchi Does it make more sense to change the versioning requirements or to update the code / require new versions?

**Comment by ktehranchi** [comment]
I think it makes sense to keep the latest versions of pypsa and pandas.... I will update the code that's causing this issue. 

@degleris1  or @jackaglad, could you post where  the `DatetimeArray._generate_range()` error is coming from?

**Comment by degleris1** [comment]
Here's the pandas one with `pandas=2.0.3`:
```
Finished job 7.
1 of 10 steps (10%) done
Traceback (most recent call last):
  File "/Users/degleris/Documents/31-Code/pypsa-breakthroughenergy-usa/workflow/.snakemake/scripts/tmp4znc4vwp.create_network_from_zenodo.py", line 266, in <module>
    pd.date_range(freq="h", start="2016-01-01", end="2017-01-01", closed="left")
  File "/Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/indexes/datetimes.py", line 945, in date_range
    dtarr = DatetimeArray._generate_range(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DatetimeArray._generate_range() got an unexpected keyword argument 'closed'
[Wed Jul  5 16:09:37 2023]
Error in rule create_network:
    jobid: 10
    input: data/base_grid/bus.csv, data/base_grid/branch.csv, data/base_grid/dcline.csv, data/base_grid/plant.csv, data/base_grid/wind.csv, data/base_grid/solar.csv, data/base_grid/hydro.csv, data/base_grid/demand.csv, data/base_grid/bus2sub.csv, data/base_grid/sub.csv, repo_data/pypsa_eur_costs.csv
    output: data/base_grid/western/bus2sub.csv, data/base_grid/western/sub.csv, resources/western/elec.nc
    log: logs/create_network/western.log (check log file(s) for error details)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-07-05T160855.607148.snakemake.log
```

I'll find the `pypsa.networkclustering` one in a second.

**Comment by degleris1** [comment]
Here is the error with `pypsa=0.24.0`
```
[Wed Jul  5 16:21:22 2023]
rule cluster_network:
    input: resources/western/elec_ss.nc, resources/western/regions_onshore_s.geojson, resources/western/regions_offshore_s.geojson, data/base_grid/western/bus2sub.csv, repo_data/pypsa_eur_costs.csv
    output: resources/western/elec_s_300.nc, resources/western/regions_onshore_s_300.geojson, resources/western/regions_offshore_s_300.geojson, resources/western/busmap_s_300.csv, resources/western/linemap_s_300.csv
    log: logs/cluster_network/western/elec_s_300.log
    jobid: 5
    benchmark: benchmarks/cluster_network/western/elec_s_300
    reason: Missing output files: resources/western/elec_s_300.nc, resources/western/regions_offshore_s_300.geojson, resources/western/regions_onshore_s_300.geojson; Input files updated by another job: resources/western/elec_ss.nc, resources/western/regions_onshore_s.geojson, data/base_grid/western/bus2sub.csv, resources/western/regions_offshore_s.geojson
    wildcards: interconnect=western, clusters=300
    resources: tmpdir=/var/folders/8r/yqy_8fmd31z7_95zdbxhwcjh0000gn/T, mem_mb=6000, mem_mib=5723

/Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa/lib/python3.11/site-packages/pypsa/networkclustering.py:16: UserWarning: The namespace `pypsa.networkclustering` is deprecated and will be removed in PyPSA v0.24. Please use `pypsa.clustering.spatial instead`.
  warnings.warn(
INFO:pypsa.io:Imported network elec_ss.nc has buses, carriers, generators, lines, links, loads
Traceback (most recent call last):
  File "/Users/degleris/Documents/31-Code/pypsa-breakthroughenergy-usa/workflow/.snakemake/scripts/tmpunfvz6qz.cluster_network_eur.py", line 421, in <module>
    clustering = clustering_for_n_clusters(n, n_clusters, custom_busmap, aggregate_carriers,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/degleris/Documents/31-Code/pypsa-breakthroughenergy-usa/workflow/.snakemake/scripts/tmpunfvz6qz.cluster_network_eur.py", line 313, in clustering_for_n_clusters
    bus_strategies, generator_strategies = get_aggregation_strategies(aggregation_strategies)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/degleris/Documents/31-Code/pypsa-breakthroughenergy-usa/workflow/scripts/_helpers.py", line 220, in get_aggregation_strategies
    from pypsa.networkclustering import _make_consense
ImportError: cannot import name '_make_consense' from 'pypsa.networkclustering' (/Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa/lib/python3.11/site-packages/pypsa/networkclustering.py)
[Wed Jul  5 16:21:35 2023]
Error in rule cluster_network:
    jobid: 5
    input: resources/western/elec_ss.nc, resources/western/regions_onshore_s.geojson, resources/western/regions_offshore_s.geojson, data/base_grid/western/bus2sub.csv, repo_data/pypsa_eur_costs.csv
    output: resources/western/elec_s_300.nc, resources/western/regions_onshore_s_300.geojson, resources/western/regions_offshore_s_300.geojson, resources/western/busmap_s_300.csv, resources/western/linemap_s_300.csv
    log: logs/cluster_network/western/elec_s_300.log (check log file(s) for error details)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-07-05T161711.942129.snakemake.log
```

**Comment by ktehranchi** [comment]
I've pushed changes that resolve these issues. Let me know if they look good on your end. You should run `conda env update --file environment.yaml` 

- updated code for the `DateRange` issue
-  specified `pypsa==0.23.0` version for the clustering issue. This is a temporary solution since the better solution is to add snakemake modules to pull the clustering rule directly from the latest European version. Will get to that soon.

**Comment by degleris1** [comment]
> Also note that with the newer versions in the master branch. you will need to set the config `load_data: use_breakthrough: true` and others false if you want to use the original breakthrough data

The alternative being your updated version of the data?

**Comment by ktehranchi** [comment]
yep- if you choose `use_eia = true` then you can choose which historical year of demand (2015-2023). If you set `use_ads= true` then it will load the WECC ADS forecast for 2023 demand.

I'm working on matching the historical weather year renewable profiles with that demand data, hopefully getting it done this week.
